# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litestream < Formula
  desc "Streaming replication for SQLite databases"
  homepage "https://litestream.io"
  version "0.5.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.14/litestream-0.5.14-darwin-x86_64.tar.gz"
      sha256 "7432fc0a8c796c6a86f57d13a771d01795c3ea90da124c37e5af501cd08db0e4"

      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.14/litestream-0.5.14-darwin-arm64.tar.gz"
      sha256 "d4a1f810387d66264e4c9b0c3a29aa3d5dff2d6f53cb4c55ec093594d2ef94c3"

      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.14/litestream-0.5.14-linux-x86_64.tar.gz"
      sha256 "32083dd2af13840b273c538360b828368d7b82bbaa2c641106052dc7814ed956"
      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.14/litestream-0.5.14-linux-armv6.tar.gz"
      sha256 "5d96b73ffeca1c5714e3e10888e8e2130cfb769b956d4cbb5951f62f8a59d3d8"
      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.14/litestream-0.5.14-linux-arm64.tar.gz"
      sha256 "b49b3d01fb0a8b4d426ee613c080fba44acae0551587dc43525dcd93eee64b4f"
      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
  end

  test do
    system "#{bin}/litestream", "version"
  end
end
