# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litestream < Formula
  desc "Streaming replication for SQLite databases"
  homepage "https://litestream.io"
  version "0.5.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.9/litestream-0.5.9-darwin-x86_64.tar.gz"
      sha256 "61750da940ba00dce5a582fc549848754270acc6dca7643a8afea5cf32d45e9d"

      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.9/litestream-0.5.9-darwin-arm64.tar.gz"
      sha256 "1ccff96084d3e0faf4f8fabd22931fd774718f43b920480c48cbf366a558146d"

      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.9/litestream-0.5.9-linux-x86_64.tar.gz"
      sha256 "e8612ef5424802723e8cfa2d07a182df60f9af71839b5ff5ef1e80dff38efbdd"
      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.9/litestream-0.5.9-linux-armv6.tar.gz"
      sha256 "580ea703e76f8db153e1f16a61dbf0acb44961afc6d48f64681dff53bbd96c97"
      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benbjohnson/litestream/releases/download/v0.5.9/litestream-0.5.9-linux-arm64.tar.gz"
      sha256 "330e290f98ecf00ac3b8b2e2f038d81ada2712da86a9466d3187f02ded269821"
      define_method(:install) do
        bin.install "litestream"
        etc.install "etc/litestream.yml" => "litestream.yml"
      end
    end
  end

  test do
    system "#{bin}/litestream", "version"
  end
end
